config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # root 'information#index'
  root 'users#index'
  resources :information
  resources :users, only: [:index, :create]
  resources :sessions, only: [:create]
  get 'information/show/:id' => "information#show"
  get 'information/delete/:id' => "information#delete"
  get 'log_out' => "sessions#destroy"
  get 'users/reload' => "users#reload"
  get 'users/index' => "users#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/information.rb
class Information < ApplicationRecord
    validates :name, :age, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # has_secure_password
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :name, :email, :password_digest, presence: true
  validates :email, format: { with: VALID_EMAIL_REGEX }, uniqueness: { :case_sensitive => false}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception
   
    before_action :set_cache_buster
    
private
    def set_cache_buster
      response.headers["Cache-Control"] = "no-cache, no-store, max-age=0, must-revalidate"
      #Cache-Control => HTTP/1.0 && Pragma => HTTP/1.1
      response.headers["Pragma"] = "no-cache"
      response.headers["Expires"] = "Fri, 28 March 2019 00:00:00 GMT"
    end

    def current_user
       if session[:user_id]
        User.find(session[:user_id])
       end
    end

    def require_login
      unless session[:user_id]
        flash[:errors] = ["You must login first"]
        redirect_to root_path
      end
    end
end

app/controllers/information_controller.rb
class InformationController < ApplicationController

    before_action :require_login
    before_action :set_cache_buster

    def index
      @info = Information.all
    end
    
    def new
      @info = Information.new
    end

    def create
      @info = Information.new(information_params)
      if @info.save
         redirect_to information_index_path
      else
           flash[:errors] = @info.errors.full_messages
           redirect_to '/information/new'
      end  
    end

    def edit
        @info = Information.find(params[:id])
    end

    def update
        @info = Information.find(params[:id])
        if @info.update(information_params)
            redirect_to information_index_path
        end
    end

    def information_params
        params.require(:information).permit(:name, :age)
    end

    def show
        @info = Information.find(params[:id])
    end

    def delete
        @info = Information.find(params[:id])
        @info.destroy
        redirect_to information_index_path
    end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    def create
        # fail
        user = User.find_by(email: params[:email])
        if user && user.password_digest == params[:password_digest]
            session[:user_id] = user.id 
            redirect_to information_index_path
        else 
            flash[:errors] = ["Invalid Combination", "Try back later!!!"]
            redirect_back fallback_location: users_path
        end
    end

    def destroy
        reset_session
        redirect_to root_path
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def index
        @user = User.new
    end

    def create
        user = User.new(user_params) #user is the model name
        if user.save
           session[:user_id] = user.id
        #    flash[:errors] = ["Account successfully created"]
           redirect_to information_index_path
        else
            flash[:errors] = user.errors.full_messages
            redirect_to root_path
        end
    end

private
    def user_params
        params.require(:user).permit(:name, :email, :password_digest)
        # params.requre(modelname)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/information_helper.rb
module InformationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/information/_form.html.erb
<%= form_for(@info) do |f| %>
    <p> NAME: </p>
    <%= f.text_field :name %> <br/>
    <p> AGE: </p>
    <%= f.text_field :age %><br/>
    
    <%= f.submit %>
<% end %>

app/views/information/edit.html.erb
<%= render partial: "information/form" %>

app/views/information/index.html.erb
<p> THIS DISPLAY USER'S INFORMATION </p>

<table>

    <% @info.each do |val| %>
          <tr>
              <td> <%= val.name %> </td>
              <td> <%= val.age %> </td>
              <td> <%= link_to('SHOW PROFILE', {
                  "controller": "information",
                  "action": "show",
                  "id":val.id
              }) %> </td>
              <td> <%= link_to('DELETE PROFILE', {
                  "controller": "information",
                  "action": "delete",
                  "id":val.id,
                   data:{ confirm: 'Are you sure?' }
               }) %> </td>
               <td>
               <%= link_to('EDIT PROFILE', {
                  "controller": "information",
                  "action": "edit",
                  "id":val.id
               }) %>
               </td>
          </tr>    
    <% end %>

</table>

<%= link_to('ADD INFORMATION', {
    "controller" => "information",
    "action" => "new"
}) 
%> | <%= link_to('LOG OUT', '/log_out' ) %>

app/views/information/new.html.erb
<% if flash[:errors] %>
   <% flash[:errors].each do |e| %>
        <p> <%= e %> </p>
   <% end %>    
<% end %>
<%= render partial: "information/form" %>

app/views/information/show.html.erb
<p><%= @info.id %>, <%= @info.name %>, <%= @info.age %> </p> 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/index.html.erb
<html>

<p> Login and Registeration </p>


<script type="text/javascript">
    (function(){
        if( window.localStorage )
         {
          if( !localStorage.getItem('firstLoad') )
           {
               localStorage['firstLoad'] = true;
               window.location.reload();
            }  
            else
               localStorage.removeItem('firstLoad');
         }
})();
</script>

<body>
   <% if flash[:errors] %>
       <% flash[:errors].each do |e|  %>
           <p><%= e %></p>
       <% end %>
   <% end %>

  <p> REGISTERATION FORM </p>

   <%= form_for @user do |f| %>
       <%= f.text_field :name %> <br/>
       <%= f.email_field :email %> <br/>
       <%= f.password_field :password_digest %> <br/>
       <%= f.submit %>
   <% end %>

<br/>

    <p> LOGIN FORM </p>

    <%= form_tag sessions_path do %>
       <%= email_field_tag :email %>
       <%= password_field_tag :password_digest %>   
       <%= submit_tag "Sign In" %>
    <% end %>


  </body>

</html>